name: quick_click_match
description: Fast-paced deck matching game built for online + local multiplayer
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ">=3.0.0 <4.0.0"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/textures/
    - assets/menu/
    - assets/menu/avatars/
    - assets/deck_assets/
    - assets/deck_assets/Animals - Large/
    - assets/deck_assets/Animals - Small/
    - assets/deck_assets/Letters/
    - assets/audio/
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.1
  archive: any
  image: ^3.0.1
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^9.0.0
  confetti: ^0.6.0
  amazon_cognito_identity_dart_2: ^3.8.1
  http: ^1.1.0
  google_fonts: ^6.2.1
  # Add other dependencies here as needed
  web_socket_channel: ^2.4.0
    # Contacts access
  # share_plus: ^7.2.2
  permission_handler: ^11.0.1
  audioplayers: ^5.2.1
  # UI components
  cupertino_icons: ^1.0.2
dev_dependencies:
  web : ^1.1.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.2
  build_runner: ^2.4.7
  idb_shim: ^2.2.0
  file_picker: ^8.3.6
  
